name: ðŸ› Bug
description: Report a bug or an unexpected behavior
labels: [bug]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to EcoLogits! ðŸ’ª

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. ðŸ™
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        import ecologits

        ...
      render: Python
