name: Feature request
description: Suggest a new feature for EcoLogits
labels: [feature request]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to EcoLogits! 💪

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give as much detail as possible about the feature you would like to suggest. 🙏

        You might like to add:
        * A demo of how code might look when using the feature
        * Your use case(s) for the feature
        * Why the feature should be added to EcoLogits (as opposed to another library or just implemented in your code)
    validations:
      required: true
